name: Build-Pipeline-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - main
    - develop

pr:
  branches:
    include:
    - main

# Use self-hosted agent instead of Microsoft-hosted
pool:
  name: 'Default'  # Changed from vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildJob
  displayName: 'Build on Self-Hosted Agent'
  steps:
  
  - script: |
      echo "Build triggered by: $(Build.Reason)"
      echo "Source branch: $(Build.SourceBranch)"
      echo "Running on self-hosted agent"
      echo "Current time: $(date)"
    displayName: 'Display Build Info'
  
  - script: |
      echo "Installing dependencies..."
      # Add your build steps here
      echo "Build completed on local agent"
    displayName: 'Build Application'
  
  - script: |
      echo "Creating build artifacts..."
      mkdir -p $(Build.ArtifactStagingDirectory)/app
      echo "Artifact created" > $(Build.ArtifactStagingDirectory)/app/build-output.txt
    displayName: 'Create Artifacts'
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Artifacts'